[FAN-228] Add pagination to nft marketplace
bouncefinance/bounce-market pull request #108
Opened 2021-06-25 08:38 UTC by sidorovkirill

https://fangible.atlassian.net/browse/FAN-228

2021-06-25 14:59 UTC, Antroll requested changes

2021-06-25 14:59 UTC, Antroll commented on src/modules/market/components/Products/useProductsStyles.ts
> +export const useProductsStyles = makeStyles((theme) => ({
Please move pagination styles to the `uiKit`.

2021-06-25 14:59 UTC, Antroll commented on src/modules/market/components/Products/useProductsStyles.ts
> +    '& .MuiPaginationItem-root': {
Try to use [PaginationItem classes api](https://material-ui.com/api/pagination-item/#css) for style definitions instead of css cascade.

2021-06-30 10:57 UTC, Antroll approved these changes

2021-06-30 16:24 UTC, BigBadAlien approved these changes

2021-06-30 16:24 UTC, BigBadAlien commented on src/modules/market/components/Products/Products.tsx
> +  const paginationCount = useMemo(() => {
`pagesCount`?

can we move the calculation inside action?

2021-06-30 16:24 UTC, BigBadAlien commented on src/modules/uiKit/Pagination/Pagination.tsx
> +  const itemCreator = (itemProps: PaginationItemProps) => (
```suggestion
  const renderItem = (itemProps: PaginationItemProps) => (
```

Let's keep it `renderItem` to not add variet of namings

2021-07-01 14:17 UTC, merged